
package aldiwan;

import java.sql.*;
import javax.swing.*;


public class CreditForm extends javax.swing.JFrame {
    
    // declare a double to save it to database
    // declare as public here, for other objects to use it.
    public static double dblBillAmount;

    // ### Constructor Polymorphism ###
    public CreditForm() {
        initComponents();
    }
    /**
     * Creates new form CreditForm
     * Pass double to the constructor
     * @param billAmount
     */
    public CreditForm(double billAmount) {
        
        dblBillAmount = billAmount;
        
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("Pay By Credit Card");
        initComponents();
        setLocationRelativeTo(null); // Center the window
        // get the logged in person name from the SessionPerson Class
        lblCurrentPerson.setText("User: " + SessionPerson.getCurrentPersonName());
        lblAmountWithdraw.setText("Amount to withdraw: " + billAmount);
    }// CreditForm() Constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCreditCancel = new javax.swing.JButton();
        btnCreditDone = new javax.swing.JButton();
        lblAmountWithdraw = new javax.swing.JLabel();
        txtCardNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNameOnCard = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerExpDate = new javax.swing.JSpinner();
        lblCurrentPerson = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(745, 584));
        setPreferredSize(new java.awt.Dimension(745, 584));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(217, 206, 197));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreditCancel.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        btnCreditCancel.setForeground(new java.awt.Color(64, 31, 52));
        btnCreditCancel.setText("Cancel");
        btnCreditCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreditCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 140, -1));

        btnCreditDone.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        btnCreditDone.setForeground(new java.awt.Color(64, 31, 52));
        btnCreditDone.setText("Done");
        btnCreditDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditDoneActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreditDone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 140, -1));

        lblAmountWithdraw.setFont(new java.awt.Font("Dialog.plain", 1, 24)); // NOI18N
        lblAmountWithdraw.setForeground(new java.awt.Color(64, 31, 52));
        lblAmountWithdraw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAmountWithdraw.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(lblAmountWithdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 410, 70));

        txtCardNumber.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        txtCardNumber.setForeground(new java.awt.Color(64, 31, 52));
        jPanel1.add(txtCardNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 280, 40));

        jLabel2.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 31, 52));
        jLabel2.setText("Name on Card");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, 40));

        txtNameOnCard.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        txtNameOnCard.setForeground(new java.awt.Color(64, 31, 52));
        jPanel1.add(txtNameOnCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 280, 40));

        jLabel3.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(64, 31, 52));
        jLabel3.setText("Expiry Date");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, 40));

        jLabel4.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(64, 31, 52));
        jLabel4.setText("Credit Card #");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, 40));

        jSpinnerExpDate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jSpinnerExpDate.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerExpDate.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerExpDate, "dd-MM-yyyy"));
        jPanel1.add(jSpinnerExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 280, 40));

        lblCurrentPerson.setFont(new java.awt.Font("Dialog.plain", 1, 24)); // NOI18N
        lblCurrentPerson.setForeground(new java.awt.Color(64, 31, 52));
        lblCurrentPerson.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentPerson.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(lblCurrentPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 410, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreditCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditCancelActionPerformed
        // close the Credit Card frame, 
        // then the menu will appear
        this.dispose();
    }//GEN-LAST:event_btnCreditCancelActionPerformed

    private void btnCreditDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditDoneActionPerformed
        try{ 
            // prepare the values
            // get the current Person ID from SessionPerson Class
            int current_person_id = SessionPerson.getCurrentPersonID();
            double cash_Withdraw = dblBillAmount;
            String card_no = txtCardNumber.getText();
            String name_On_Card = txtNameOnCard.getText();

            // Retrieve the selected date as a java.util.Date
            java.util.Date selectedDate = (java.util.Date) jSpinnerExpDate.getValue();
            // Convert the java.util.Date to java.sql.Date
            java.sql.Date exp_date = new java.sql.Date(selectedDate.getTime());

            // DBConnection.connection ==> declared in the DBConnection CLASS
            Connection conn = (Connection) DBConnection.connection;

            int quantity = SessionPerson.getTableRowsCount();
            String sqlInsertOrders = "INSERT INTO orders (user_id, item_id, type, quantity, total_cost)"
            + " VALUES (?,?,?,?,?)";
            PreparedStatement preparedStatement = conn.prepareStatement (sqlInsertOrders);
            preparedStatement.setInt(1, current_person_id); // for customer column too
            preparedStatement.setInt(2, current_person_id);
            preparedStatement.setString(3, "Credit");
            preparedStatement.setInt(4, quantity);
            preparedStatement.setDouble(5, dblBillAmount);
            int rowsAffected = preparedStatement.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this,
                    "Order Saved in ORDERS Successfully",
                    "Save Done",
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                    "Failed to save in ORDERS table",
                    "Save Failed",
                    JOptionPane.ERROR_MESSAGE);
            }// if (rowsAffected)
      

            String sql = "INSERT INTO paycredit (customer_id, person_id, cash_withdraw, cardNo, name_on_card, expDate)"
                    + "VALUES (?,?,?,?,?,?)";
            PreparedStatement ps = conn.prepareStatement (sql);
            ps.setInt(1, current_person_id); // for customer column too
            ps.setInt(2, current_person_id);
            ps.setDouble(3, cash_Withdraw);
            ps.setString(4, card_no);
            ps.setString(5, name_On_Card);
            ps.setDate(6, exp_date);
            // Execute the query
            rowsAffected = ps.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this,
                    "Order Saved in PayCredit Successfully",
                    "Save Done",
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                    "Failed to save Order Information",
                    "Save Failed",
                    JOptionPane.ERROR_MESSAGE);
            }// if (rowsAffected)
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(this,
                    """
                    Failed Connect
                    \nReason:\nCredit Form\n""" + e.getMessage(),
                    "Connection Failed",
                    JOptionPane.ERROR_MESSAGE);
        } // try catch block
        
        // save to database then close the Credit Card frame, 
        // then the menu will appear to input a new order
        this.dispose();
    }//GEN-LAST:event_btnCreditDoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // call the polymorphismed class with no arguments
                new CreditForm().setVisible(true);
            }
        });
    }// main()

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreditCancel;
    private javax.swing.JButton btnCreditDone;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerExpDate;
    private javax.swing.JLabel lblAmountWithdraw;
    private javax.swing.JLabel lblCurrentPerson;
    private javax.swing.JTextField txtCardNumber;
    private javax.swing.JTextField txtNameOnCard;
    // End of variables declaration//GEN-END:variables
} // CreditForm{}




