
package aldiwan;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.*;
import javax.swing.*;

public class DeliveryForm extends javax.swing.JFrame {

    // declare a double to save it to database
    // declare as public here, for other objects to use it.
    public static double dblAmountDue;
    public static double dlv_fee;
    
    // ### Constructor polymorphism ###
    public DeliveryForm() {
        initComponents();
    }
    public DeliveryForm(double bill) {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("Delivery Order");
        setLocationRelativeTo(null); // Center the window
        // get the logged in person name from the SessionPerson Class
        dblAmountDue = bill;
        lblUser.setText("User: " + SessionPerson.getCurrentPersonName());
        lblDueTotal.setText("Due Amount Total: " + bill);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblDueTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDeliveryFee = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCustomerAddress = new javax.swing.JTextField();
        txtCustomerTel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnDone = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(745, 584));
        setPreferredSize(new java.awt.Dimension(745, 584));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(234, 233, 231));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUser.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(64, 31, 52));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 490, 50));

        lblDueTotal.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        lblDueTotal.setForeground(new java.awt.Color(64, 31, 52));
        lblDueTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDueTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(lblDueTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 490, 50));

        jLabel1.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(64, 31, 52));
        jLabel1.setText("Delivery Fee");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 160, 30));

        txtDeliveryFee.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        txtDeliveryFee.setForeground(new java.awt.Color(64, 31, 52));
        txtDeliveryFee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDeliveryFeeFocusLost(evt);
            }
        });
        txtDeliveryFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeliveryFeeActionPerformed(evt);
            }
        });
        jPanel1.add(txtDeliveryFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 290, 30));

        jLabel2.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 31, 52));
        jLabel2.setText("Customer Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 150, 30));

        txtCustomerName.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        txtCustomerName.setForeground(new java.awt.Color(64, 31, 52));
        jPanel1.add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 290, 30));

        jLabel3.setFont(new java.awt.Font("Dialog.plain", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(64, 31, 52));
        jLabel3.setText("Customer Address");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 150, 20));

        txtCustomerAddress.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        txtCustomerAddress.setForeground(new java.awt.Color(64, 31, 52));
        jPanel1.add(txtCustomerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 290, 30));

        txtCustomerTel.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        txtCustomerTel.setForeground(new java.awt.Color(64, 31, 52));
        jPanel1.add(txtCustomerTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 290, 30));

        jLabel4.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(64, 31, 52));
        jLabel4.setText("Customer Tel");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 150, 30));

        btnDone.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        btnDone.setForeground(new java.awt.Color(64, 31, 52));
        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });
        jPanel1.add(btnDone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 140, 40));

        btnCancel.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(64, 31, 52));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDeliveryFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeliveryFeeActionPerformed
        // in case user pressed Enter Key
        if ( ! txtDeliveryFee.getText().equals("")){
            dlv_fee = Double.parseDouble(txtDeliveryFee.getText());
            double totalFee = dblAmountDue + dlv_fee;
            lblDueTotal.setText(Double.toString(totalFee));
        }
    }//GEN-LAST:event_txtDeliveryFeeActionPerformed
    
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // close the Credit Card frame, 
        // then the menu will appear
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtDeliveryFeeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDeliveryFeeFocusLost
        // in case the user pressed TAB, or Clicked the mouse.
        if ( ! txtDeliveryFee.getText().equals("")){
            dlv_fee = Double.parseDouble(txtDeliveryFee.getText());
            double totalFee = dblAmountDue + dlv_fee;
            lblDueTotal.setText(Double.toString(totalFee));
        }
    }//GEN-LAST:event_txtDeliveryFeeFocusLost

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        try{
            // prepare the values
            // get the current Person ID from SessionPerson Class
            int current_person_id = SessionPerson.getCurrentPersonID();
            // dlv_fee is calculated up above
            String customerName = txtCustomerName.getText();
            String customerAddress = txtCustomerAddress.getText();
            String customerTel = txtCustomerTel.getText();

            // dblAmountDue AND dlv_fee are public variables 
            double totalFee = dblAmountDue + dlv_fee;

            // go through 3 steps to covert a double to BigDecimal then back to double
            // Convert the double to BigDecimal
            BigDecimal twoDecimal_iTotal = new BigDecimal(totalFee);
            // Set the scale to 2 decimal places with rounding
            BigDecimal formatted_iTotal = twoDecimal_iTotal.setScale(2, RoundingMode.HALF_UP);
            // Convert back to double to display it.
            totalFee = formatted_iTotal.doubleValue();
            // DBConnection.connection ==> declared in the DBConnection CLASS
            Connection conn = (Connection) DBConnection.connection;
            
            int quantity = SessionPerson.getTableRowsCount();
            String sqlInsertOrders = "INSERT INTO orders (user_id, item_id, type, quantity, total_cost)"
            + " VALUES (?,?,?,?,?)";
            PreparedStatement preparedStatement = conn.prepareStatement (sqlInsertOrders);
            preparedStatement.setInt(1, current_person_id); // for customer column too
            preparedStatement.setInt(2, current_person_id);
            preparedStatement.setString(3, "Takeaway");
            preparedStatement.setInt(4, quantity);
            preparedStatement.setDouble(5, totalFee);
            int rowsAffected = preparedStatement.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this,
                    "Order Saved in ORDERS Successfully",
                    "Save Done",
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                    "Failed to save in ORDERS table",
                    "Save Failed",
                    JOptionPane.ERROR_MESSAGE);
            }// if (rowsAffected)
      
            String sqlInsertTakeaway = "INSERT INTO takeaway (customer_id, order_id, delivery_fees, customer_name, "
                    + "customer_addr, customer_tel, amount_due) "
                    + "VALUES (?,?,?,?,?,?,?)";
            PreparedStatement ps = conn.prepareStatement (sqlInsertTakeaway);
            
            ps.setInt(1, current_person_id); // for customer column too
            ps.setInt(2, current_person_id);
            ps.setDouble(3, dlv_fee);
            ps.setString(4, customerName);
            ps.setString(5, customerAddress);
            ps.setString(6, customerTel);
            ps.setDouble(7, totalFee);
            // Execute the query
            rowsAffected = ps.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this,
                    "Takeaway Order Saved Successfully",
                    "Save Done",
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                    "Failed to save Takeaway Order Information",
                    "Save Failed",
                    JOptionPane.ERROR_MESSAGE);
            }// if (rowsAffected)
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(this,
                    """
                    Failed to Connect
                    \nReason:\nDelivery Form\n""" + e.getMessage(),
                    "Connection Failed",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } // try catch block

        // save to database then close the Credit Card frame, 
        // then the menu will appear to input a new order
        this.dispose();
    }//GEN-LAST:event_btnDoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDueTotal;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTextField txtCustomerAddress;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerTel;
    private javax.swing.JTextField txtDeliveryFee;
    // End of variables declaration//GEN-END:variables
}
