
package aldiwan;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.math.*;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Menu extends javax.swing.JFrame {
    
// declare public String fullNamePub, to be able to use it inside other objects
public static String fullNamePub="";
    
    // create a table model as instance variable, so it can be reached from all objects
    private final DefaultTableModel model;
    
    public Menu(String fullname, String role) {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setExtendedState(Menu.MAXIMIZED_BOTH); // Maximize the window
        setLocationRelativeTo(null);
        setTitle("ALDIWAN Restaurant Menu");
        lblMenuTitle.setText("Hello: " + fullname);
        fullNamePub = fullname; 
        
        mainContentPanel.setLayout(new BorderLayout()); // Use BorderLayout for resizing
        setContentPane(mainContentPanel);
        
        // Allow the inner jPanels to resize inside the outer jPanel
        mainContentPanel.add(usernamePanel, BorderLayout.NORTH); 
        mainContentPanel.add(contentsPanel, BorderLayout.CENTER); 
                
        // set the panels widths to 60% and 40%, and respond to window sizing
        menuItemsPanel.setPreferredSize(new Dimension((int) 
                (contentsPanel.getWidth() * 0.6), contentsPanel.getHeight()));
        pricesPanel.setPreferredSize(new Dimension((int) 
                (contentsPanel.getWidth() * 0.4), contentsPanel.getHeight()));
        
        // declare the table model inside the constructor.
        // so it can be accessed from all buttons
        model = (DefaultTableModel) reciptModel.getModel();
    } // Menu() Constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContentPanel = new javax.swing.JPanel();
        usernamePanel = new javax.swing.JPanel();
        lblMenuTitle = new javax.swing.JLabel();
        contentsPanel = new javax.swing.JPanel();
        menuItemsPanel = new javax.swing.JPanel();
        PizzaHeart = new javax.swing.JButton();
        doubleBurger = new javax.swing.JButton();
        burger = new javax.swing.JButton();
        phileCheeseSteak = new javax.swing.JButton();
        phileDouble = new javax.swing.JButton();
        phileLong = new javax.swing.JButton();
        cola2Leter = new javax.swing.JButton();
        cola1Leter = new javax.swing.JButton();
        colaCan = new javax.swing.JButton();
        frise = new javax.swing.JButton();
        pastaPan = new javax.swing.JButton();
        spagetti = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnNewReceipt = new javax.swing.JButton();
        pricesPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reciptModel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        txtTax = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnCash = new javax.swing.JButton();
        btnDelivery = new javax.swing.JButton();
        btnCredit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usernamePanel.setBackground(new java.awt.Color(89, 44, 73));

        lblMenuTitle.setFont(new java.awt.Font("Dialog.plain", 1, 24)); // NOI18N
        lblMenuTitle.setForeground(new java.awt.Color(234, 233, 231));
        lblMenuTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuTitle.setText("username");

        javax.swing.GroupLayout usernamePanelLayout = new javax.swing.GroupLayout(usernamePanel);
        usernamePanel.setLayout(usernamePanelLayout);
        usernamePanelLayout.setHorizontalGroup(
            usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMenuTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        usernamePanelLayout.setVerticalGroup(
            usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentsPanel.setBackground(new java.awt.Color(201, 141, 117));

        menuItemsPanel.setBackground(new java.awt.Color(217, 193, 180));

        PizzaHeart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aldiwan/images/pizza5Heart.jpg"))); // NOI18N
        PizzaHeart.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PizzaHeart.setContentAreaFilled(false);
        PizzaHeart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PizzaHeartActionPerformed(evt);
            }
        });

        doubleBurger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aldiwan/images/b2double.jpg"))); // NOI18N
        doubleBurger.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        doubleBurger.setContentAreaFilled(false);
        doubleBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleBurgerActionPerformed(evt);
            }
        });

        burger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aldiwan/images/burger2.png"))); // NOI18N
        burger.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        burger.setContentAreaFilled(false);
        burger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burgerActionPerformed(evt);
            }
        });

        phileCheeseSteak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aldiwan/images/Cheesesteak1.jpg"))); // NOI18N
        phileCheeseSteak.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        phileCheeseSteak.setContentAreaFilled(false);
        phileCheeseSteak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phileCheeseSteakActionPerformed(evt);
            }
        });

        phileDouble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aldiwan/images/Cheesesteak2.jpeg"))); // NOI18N
        phileDouble.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        phileDouble.setContentAreaFilled(false);
        phileDouble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phileDoubleActionPerformed(evt);
            }
        });

        phileLong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aldiwan/images/Cheesesteak3.jpg"))); // NOI18N
        phileLong.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        phileLong.setContentAreaFilled(false);
        phileLong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phileLongActionPerformed(evt);
            }
        });

        cola2Leter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aldiwan/images/colaBottle.jpg"))); // NOI18N
        cola2Leter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cola2Leter.setContentAreaFilled(false);
        cola2Leter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cola2LeterActionPerformed(evt);
            }
        });

        cola1Leter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aldiwan/images/colaBottle200.jpg"))); // NOI18N
        cola1Leter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cola1Leter.setContentAreaFilled(false);
        cola1Leter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cola1LeterActionPerformed(evt);
            }
        });

        colaCan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aldiwan/images/colaCan.jpg"))); // NOI18N
        colaCan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        colaCan.setContentAreaFilled(false);
        colaCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colaCanActionPerformed(evt);
            }
        });

        frise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aldiwan/images/ff.png"))); // NOI18N
        frise.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        frise.setContentAreaFilled(false);
        frise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friseActionPerformed(evt);
            }
        });

        pastaPan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aldiwan/images/pasta1 pan.jpg"))); // NOI18N
        pastaPan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pastaPan.setContentAreaFilled(false);
        pastaPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastaPanActionPerformed(evt);
            }
        });

        spagetti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aldiwan/images/pasta2.jpg"))); // NOI18N
        spagetti.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        spagetti.setContentAreaFilled(false);
        spagetti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spagettiActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnNewReceipt.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        btnNewReceipt.setText("New Receipt");
        btnNewReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewReceiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuItemsPanelLayout = new javax.swing.GroupLayout(menuItemsPanel);
        menuItemsPanel.setLayout(menuItemsPanelLayout);
        menuItemsPanelLayout.setHorizontalGroup(
            menuItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItemsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuItemsPanelLayout.createSequentialGroup()
                            .addComponent(phileDouble, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(phileLong, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cola2Leter, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cola1Leter, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuItemsPanelLayout.createSequentialGroup()
                            .addComponent(colaCan, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(frise, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pastaPan, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(spagetti, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(menuItemsPanelLayout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(66, 66, 66)
                            .addComponent(btnNewReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(menuItemsPanelLayout.createSequentialGroup()
                        .addComponent(PizzaHeart, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(doubleBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(burger, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(phileCheeseSteak, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        menuItemsPanelLayout.setVerticalGroup(
            menuItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItemsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phileCheeseSteak, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(burger, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doubleBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PizzaHeart, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(menuItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cola1Leter, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cola2Leter, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phileLong, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phileDouble, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(menuItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spagetti, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pastaPan, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frise, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colaCan, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pricesPanel.setBackground(new java.awt.Color(234, 233, 231));
        pricesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reciptModel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reciptModel.setFont(new java.awt.Font("Dialog.plain", 1, 14)); // NOI18N
        reciptModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Price"
            }
        ));
        reciptModel.setAlignmentX(1.0F);
        reciptModel.setAlignmentY(1.0F);
        jScrollPane1.setViewportView(reciptModel);

        pricesPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 440, 488));

        jLabel1.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(89, 44, 73));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Sub Total");
        pricesPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 115, 44));

        jLabel2.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(89, 44, 73));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Tax");
        pricesPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, 115, 44));

        jLabel3.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(89, 44, 73));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Total");
        pricesPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 650, 115, 44));

        txtSubTotal.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        pricesPanel.add(txtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 192, 44));

        txtTax.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        pricesPanel.add(txtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 590, 192, 44));

        txtTotal.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        pricesPanel.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 650, 192, 50));

        btnCash.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        btnCash.setText("Cash");
        btnCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashActionPerformed(evt);
            }
        });
        pricesPanel.add(btnCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 720, 140, -1));

        btnDelivery.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        btnDelivery.setText("Delivery");
        btnDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveryActionPerformed(evt);
            }
        });
        pricesPanel.add(btnDelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 720, 120, -1));

        btnCredit.setFont(new java.awt.Font("Dialog.plain", 1, 18)); // NOI18N
        btnCredit.setText("Credit");
        btnCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditActionPerformed(evt);
            }
        });
        pricesPanel.add(btnCredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 720, 150, -1));

        javax.swing.GroupLayout contentsPanelLayout = new javax.swing.GroupLayout(contentsPanel);
        contentsPanel.setLayout(contentsPanelLayout);
        contentsPanelLayout.setHorizontalGroup(
            contentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentsPanelLayout.createSequentialGroup()
                .addComponent(menuItemsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pricesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentsPanelLayout.setVerticalGroup(
            contentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuItemsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pricesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainContentPanelLayout = new javax.swing.GroupLayout(mainContentPanel);
        mainContentPanel.setLayout(mainContentPanelLayout);
        mainContentPanelLayout.setHorizontalGroup(
            mainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usernamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainContentPanelLayout.setVerticalGroup(
            mainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContentPanelLayout.createSequentialGroup()
                .addComponent(usernamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose(); // close the current frame.
        new LoginFrame().setVisible(true); // show the new frame
    }//GEN-LAST:event_btnExitActionPerformed

    private void PizzaHeartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PizzaHeartActionPerformed
        String itemName = "";
        String itemPrice = "";
        // DBConnection.connection ==> declared in the DBConnection CLASS
        try{ 
            Connection conn = DBConnection.connection;
            // item_id=1 ==> first record in the menu_items table.
            String sql = "SELECT * FROM menu_items WHERE item_id = 1";
            PreparedStatement preparedStatement = conn.prepareStatement (sql);
            ResultSet resultSet = preparedStatement.executeQuery();
            if(resultSet.next()){
                // variable_name = resultSet.getString("table field title")
                itemName = resultSet.getString("name");
                itemPrice = resultSet.getString("price");
            }
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(this,
                    """
                    Failed Connect
                    \nReason:\n Login Frame Class\n """ + e.getMessage(),
                    "Connection Failed",
                    JOptionPane.ERROR_MESSAGE);
        } // try catch block
        // insert add a new row in the table 2 columns.
        model.addRow(new Object[]{itemName, itemPrice});
        // Call function to calculate receipt subtotal, tax and total.
        receipt();
    }//GEN-LAST:event_PizzaHeartActionPerformed

    private void btnNewReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewReceiptActionPerformed
        model.setRowCount(0);
        txtSubTotal.setText("");
        txtTax.setText("");
        txtTotal.setText("");
    }//GEN-LAST:event_btnNewReceiptActionPerformed

    private void doubleBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleBurgerActionPerformed
        String itemName = "";
        String itemPrice = "";
        // DBConnection.connection ==> declared in the DBConnection CLASS
        Connection conn = DBConnection.connection;
        try{ 
            // item_id = 2 ===> first record in the menu_items table.
            String sql = "SELECT * FROM menu_items WHERE item_id = 2";
            PreparedStatement preparedStatement = conn.prepareStatement (sql);
            ResultSet resultSet = preparedStatement.executeQuery();
            if(resultSet.next()){
                // variable_name = resultSet.getString("table field title")
                itemName = resultSet.getString("name");
                itemPrice = resultSet.getString("price");
            }
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(this,
                    """
                    Failed Connect
                    \nReason:\n Login Frame Class\n """ + e.getMessage(),
                    "Connection Failed",
                    JOptionPane.ERROR_MESSAGE);
        } // try catch block
        // insert add a new row in the table 2 columns.
        model.addRow(new Object[]{itemName, itemPrice});
        // function to calculate receipt subtotal, tax and total.
        receipt();
    }//GEN-LAST:event_doubleBurgerActionPerformed

    private void burgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burgerActionPerformed
        String itemName = "";
        String itemPrice = "";
        // DBConnection.connection ==> declared in the DBConnection CLASS
        Connection conn = DBConnection.connection;
        try{ 
            // item_id = 3 ===> first record in the menu_items table.
            String sql = "SELECT * FROM menu_items WHERE item_id = 3";
            PreparedStatement preparedStatement = conn.prepareStatement (sql);
            ResultSet resultSet = preparedStatement.executeQuery();
            if(resultSet.next()){
                // variable_name = resultSet.getString("table field title")
                itemName = resultSet.getString("name");
                itemPrice = resultSet.getString("price");
            }
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(this,
                    """
                    Failed Connect
                    \nReason:\n Login Frame Class\n """ + e.getMessage(),
                    "Connection Failed",
                    JOptionPane.ERROR_MESSAGE);
        } // try catch block
        // insert add a new row in the table 2 columns.
        model.addRow(new Object[]{itemName, itemPrice});
        // function to calculate receipt subtotal, tax and total.
        receipt();
    }//GEN-LAST:event_burgerActionPerformed

    private void phileCheeseSteakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phileCheeseSteakActionPerformed
        String itemName = "";
        String itemPrice = "";
        // DBConnection.connection ==> declared in the DBConnection CLASS
        Connection conn = DBConnection.connection;
        try{ 
            // item_id = 4 ===> first record in the menu_items table.
            String sql = "SELECT * FROM menu_items WHERE item_id = 4";
            PreparedStatement preparedStatement = conn.prepareStatement (sql);
            ResultSet resultSet = preparedStatement.executeQuery();
            if(resultSet.next()){
                // variable_name = resultSet.getString("table field title")
                itemName = resultSet.getString("name");
                itemPrice = resultSet.getString("price");
            }
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(this,
                    """
                    Failed Connect
                    \nReason:\n Login Frame Class\n """ + e.getMessage(),
                    "Connection Failed",
                    JOptionPane.ERROR_MESSAGE);
        } // try catch block
        // insert add a new row in the table 2 columns.
        model.addRow(new Object[]{itemName, itemPrice});
        // function to calculate receipt subtotal, tax and total.
        receipt();
    }//GEN-LAST:event_phileCheeseSteakActionPerformed

    private void phileDoubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phileDoubleActionPerformed
        String itemName = "";
        String itemPrice = "";
        // DBConnection.connection ==> declared in the DBConnection CLASS
        Connection conn = DBConnection.connection;
        try{ 
            // item_id = 5 ===> first record in the menu_items table.
            String sql = "SELECT * FROM menu_items WHERE item_id = 5";
            PreparedStatement preparedStatement = conn.prepareStatement (sql);
            ResultSet resultSet = preparedStatement.executeQuery();
            if(resultSet.next()){
                // variable_name = resultSet.getString("table field title")
                itemName = resultSet.getString("name");
                itemPrice = resultSet.getString("price");
            }
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(this,
                    """
                    Failed Connect
                    \nReason:\n Login Frame Class\n """ + e.getMessage(),
                    "Connection Failed",
                    JOptionPane.ERROR_MESSAGE);
        } // try catch block
        // insert add a new row in the table 2 columns.
        model.addRow(new Object[]{itemName, itemPrice});
        // function to calculate receipt subtotal, tax and total.
        receipt();
    }//GEN-LAST:event_phileDoubleActionPerformed

    private void phileLongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phileLongActionPerformed
        String itemName = "";
        String itemPrice = "";
        // DBConnection.connection ==> declared in the DBConnection CLASS
        Connection conn = DBConnection.connection;
        try{ 
            // item_id = 6 ===> first record in the menu_items table.
            String sql = "SELECT * FROM menu_items WHERE item_id = 6";
            PreparedStatement preparedStatement = conn.prepareStatement (sql);
            ResultSet resultSet = preparedStatement.executeQuery();
            if(resultSet.next()){
                // variable_name = resultSet.getString("table field title")
                itemName = resultSet.getString("name");
                itemPrice = resultSet.getString("price");
            }
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(this,
                    """
                    Failed Connect
                    \nReason:\n Login Frame Class\n """ + e.getMessage(),
                    "Connection Failed",
                    JOptionPane.ERROR_MESSAGE);
        } // try catch block
        // insert add a new row in the table 2 columns.
        model.addRow(new Object[]{itemName, itemPrice});
        // function to calculate receipt subtotal, tax and total.
        receipt();
    }//GEN-LAST:event_phileLongActionPerformed

    private void cola2LeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cola2LeterActionPerformed
        String itemName = "";
        String itemPrice = "";
        // DBConnection.connection ==> declared in the DBConnection CLASS
        Connection conn = DBConnection.connection;
        try{ 
            // item_id = 7 ===> first record in the menu_items table.
            String sql = "SELECT * FROM menu_items WHERE item_id = 7";
            PreparedStatement preparedStatement = conn.prepareStatement (sql);
            ResultSet resultSet = preparedStatement.executeQuery();
            if(resultSet.next()){
                // variable_name = resultSet.getString("table field title")
                itemName = resultSet.getString("name");
                itemPrice = resultSet.getString("price");
            }
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(this,
                    """
                    Failed Connect
                    \nReason:\n Login Frame Class\n """ + e.getMessage(),
                    "Connection Failed",
                    JOptionPane.ERROR_MESSAGE);
        } // try catch block
        // insert add a new row in the table 2 columns.
        model.addRow(new Object[]{itemName, itemPrice});
        // function to calculate receipt subtotal, tax and total.
        receipt();
    }//GEN-LAST:event_cola2LeterActionPerformed

    private void cola1LeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cola1LeterActionPerformed
        String itemName = "";
        String itemPrice = "";
        // DBConnection.connection ==> declared in the DBConnection CLASS
        Connection conn = DBConnection.connection;
        try{ 
            // item_id = 8 ===> first record in the menu_items table.
            String sql = "SELECT * FROM menu_items WHERE item_id = 8";
            PreparedStatement preparedStatement = conn.prepareStatement (sql);
            ResultSet resultSet = preparedStatement.executeQuery();
            if(resultSet.next()){
                // variable_name = resultSet.getString("table field title")
                itemName = resultSet.getString("name");
                itemPrice = resultSet.getString("price");
            }
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(this,
                    """
                    Failed Connect
                    \nReason:\n Login Frame Class\n """ + e.getMessage(),
                    "Connection Failed",
                    JOptionPane.ERROR_MESSAGE);
        } // try catch block
        // insert add a new row in the table 2 columns.
        model.addRow(new Object[]{itemName, itemPrice});
        // function to calculate receipt subtotal, tax and total.
        receipt();
    }//GEN-LAST:event_cola1LeterActionPerformed

    private void colaCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colaCanActionPerformed
        String itemName = "";
        String itemPrice = "";
        // DBConnection.connection ==> declared in the DBConnection CLASS
        Connection conn = DBConnection.connection;
        try{ 
            // item_id = 9 ===> first record in the menu_items table.
            String sql = "SELECT * FROM menu_items WHERE item_id = 9";
            PreparedStatement preparedStatement = conn.prepareStatement (sql);
            ResultSet resultSet = preparedStatement.executeQuery();
            if(resultSet.next()){
                // variable_name = resultSet.getString("table field title")
                itemName = resultSet.getString("name");
                itemPrice = resultSet.getString("price");
            }
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(this,
                    """
                    Failed Connect
                    \nReason:\n Login Frame Class\n """ + e.getMessage(),
                    "Connection Failed",
                    JOptionPane.ERROR_MESSAGE);
        } // try catch block
        // insert add a new row in the table 2 columns.
        model.addRow(new Object[]{itemName, itemPrice});
        // function to calculate receipt subtotal, tax and total.
        receipt();
    }//GEN-LAST:event_colaCanActionPerformed

    private void friseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friseActionPerformed
        String itemName = "";
        String itemPrice = "";
        // DBConnection.connection ==> declared in the DBConnection CLASS
        Connection conn = DBConnection.connection;
        try{ 
            // item_id = 10 ===> first record in the menu_items table.
            String sql = "SELECT * FROM menu_items WHERE item_id = 10";
            PreparedStatement preparedStatement = conn.prepareStatement (sql);
            ResultSet resultSet = preparedStatement.executeQuery();
            if(resultSet.next()){
                // variable_name = resultSet.getString("table field title")
                itemName = resultSet.getString("name");
                itemPrice = resultSet.getString("price");
            }
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(this,
                    """
                    Failed Connect
                    \nReason:\n Login Frame Class\n """ + e.getMessage(),
                    "Connection Failed",
                    JOptionPane.ERROR_MESSAGE);
        } // try catch block
        // insert add a new row in the table 2 columns.
        model.addRow(new Object[]{itemName, itemPrice});
        // function to calculate receipt subtotal, tax and total.
        receipt();
    }//GEN-LAST:event_friseActionPerformed

    private void pastaPanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastaPanActionPerformed
        String itemName = "";
        String itemPrice = "";
        // DBConnection.connection ==> declared in the DBConnection CLASS
        Connection conn = DBConnection.connection;
        try{ 
            // item_id = 11 ===> first record in the menu_items table.
            String sql = "SELECT * FROM menu_items WHERE item_id = 11";
            PreparedStatement preparedStatement = conn.prepareStatement (sql);
            ResultSet resultSet = preparedStatement.executeQuery();
            if(resultSet.next()){
                // variable_name = resultSet.getString("table field title")
                itemName = resultSet.getString("name");
                itemPrice = resultSet.getString("price");
            }
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(this,
                    """
                    Failed Connect
                    \nReason:\n Login Frame Class\n """ + e.getMessage(),
                    "Connection Failed",
                    JOptionPane.ERROR_MESSAGE);
        } // try catch block
        // insert add a new row in the table 2 columns.
        model.addRow(new Object[]{itemName, itemPrice});
        // function to calculate receipt subtotal, tax and total.
        receipt();
    }//GEN-LAST:event_pastaPanActionPerformed

    private void spagettiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spagettiActionPerformed
        String itemName = "";
        String itemPrice = "";
        // DBConnection.connection ==> declared in the DBConnection CLASS
        Connection conn = DBConnection.connection;
        try{ 
            // item_id = 12 ===> first record in the menu_items table.
            String sql = "SELECT * FROM menu_items WHERE item_id = 12";
            PreparedStatement preparedStatement = conn.prepareStatement (sql);
            ResultSet resultSet = preparedStatement.executeQuery();
            if(resultSet.next()){
                // variable_name = resultSet.getString("table field title")
                itemName = resultSet.getString("name");
                itemPrice = resultSet.getString("price");
            }
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(this,
                    """
                    Failed Connect
                    \nReason:\n Login Frame Class\n """ + e.getMessage(),
                    "Connection Failed",
                    JOptionPane.ERROR_MESSAGE);
        } // try catch block
        // insert add a new row in the table 2 columns.
        model.addRow(new Object[]{itemName, itemPrice});
        // function to calculate receipt subtotal, tax and total.
        receipt();
    }//GEN-LAST:event_spagettiActionPerformed

    private void btnCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashActionPerformed
        int current_person_id = SessionPerson.getCurrentPersonID();
        double totalCost=receipt();
        SessionPerson.setTableRowsCount(model.getRowCount());  // Directly from the JTable
        try{
            // DBConnection.connection ==> declared in the DBConnection CLASS
            Connection conn = (Connection) DBConnection.connection;
            String sqlInsert = "INSERT INTO orders (user_id, item_id, type, quantity, total_cost)"
                    + " VALUES (?,?,?,?,?)";
            PreparedStatement preparedStatement = conn.prepareStatement (sqlInsert);
            preparedStatement.setInt(1, current_person_id); // for customer column too
            preparedStatement.setInt(2, current_person_id);
            preparedStatement.setString(3, "Cash");
            preparedStatement.setInt(4, SessionPerson.getTableRowsCount());
            preparedStatement.setDouble(5, totalCost);
           
            // Execute the query
            int rowsAffected = preparedStatement.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this,
                    """
                    Order Saved
                    \nTotal: """+totalCost,
                    "Payment Done",
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                    "Failed to save Order Information",
                    "Save Failed",
                    JOptionPane.ERROR_MESSAGE);
            }// if (rowsAffected)
            }catch(SQLException e) {
            JOptionPane.showMessageDialog(this,
                    """
                    Failed to Connect
                    \nReason:\nMenu Form\n""" + e.getMessage(),
                    "Connection Failed",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } // try catch block
        
        // Clear the text fields
        model.setRowCount(0);
        txtSubTotal.setText("");
        txtTax.setText("");
        txtTotal.setText("");
    }//GEN-LAST:event_btnCashActionPerformed

    private void btnDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveryActionPerformed
        double billAmount = receipt();
        SessionPerson.setTableRowsCount(model.getRowCount());  // Directly from the JTable
        // Pass 1 double to the DeliveryForm(double)
        DeliveryForm deliveryForm = new DeliveryForm(billAmount);        
        // Open the deliveryForm window
        deliveryForm.setVisible(true);
    }//GEN-LAST:event_btnDeliveryActionPerformed

    private void btnCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditActionPerformed
        double billAmount = receipt();
        SessionPerson.setTableRowsCount(model.getRowCount());  // Directly from the JTable
        // Pass 1 double to the CreditForm(double)
        CreditForm creditForm = new CreditForm(billAmount);        
        // Open the creditForm window
        creditForm.setVisible(true);
    }//GEN-LAST:event_btnCreditActionPerformed

    
    // ----------------- Application Functions -----------------
    // ================== Function receipt() ==================
    public double receipt(){
        // sum all the values in the 3rd column "Amount"
        double sum = 0;
        double tax = 0.03; // to indicate 3%
        for (int i = 0; i< reciptModel.getRowCount(); i++){
            sum = sum + Double.parseDouble(reciptModel.getValueAt(i, 1).toString());
        }
        txtSubTotal.setText(Double.toString(sum));
        double cTotal1 = Double.parseDouble(txtSubTotal.getText());
        
        double cTax = (cTotal1 * tax);
        String iTaxTotal = String.format("$ %.2f", cTax);
        txtTax.setText(iTaxTotal); 
        
        double iTotal = cTotal1 + cTax;
        txtTotal.setText(String.format("$ %.2f",iTotal));
        
        // go through 3 steps to covert a double to BigDecimal then back to double
        // Convert the double to BigDecimal
        BigDecimal twoDecimal_iTotal = new BigDecimal(iTotal);
        // Set the scale to 2 decimal places with rounding
        BigDecimal formatted_iTotal = twoDecimal_iTotal.setScale(2, RoundingMode.HALF_UP);
        // Convert back to double to use it as a return value 
        iTotal = formatted_iTotal.doubleValue();
        
        return iTotal;
    }//recipt()
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PizzaHeart;
    private javax.swing.JButton btnCash;
    private javax.swing.JButton btnCredit;
    private javax.swing.JButton btnDelivery;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNewReceipt;
    private javax.swing.JButton burger;
    private javax.swing.JButton cola1Leter;
    private javax.swing.JButton cola2Leter;
    private javax.swing.JButton colaCan;
    private javax.swing.JPanel contentsPanel;
    private javax.swing.JButton doubleBurger;
    private javax.swing.JButton frise;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMenuTitle;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JPanel menuItemsPanel;
    private javax.swing.JButton pastaPan;
    private javax.swing.JButton phileCheeseSteak;
    private javax.swing.JButton phileDouble;
    private javax.swing.JButton phileLong;
    private javax.swing.JPanel pricesPanel;
    private javax.swing.JTable reciptModel;
    private javax.swing.JButton spagetti;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTax;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JPanel usernamePanel;
    // End of variables declaration//GEN-END:variables
}
